import type { MetricDefinition } from "@/types";

// ─────────────────────────────────────────────────────────────────────────────
// METRIC DEFINITIONS
// Central registry for all metrics displayed/logged in the app
// ─────────────────────────────────────────────────────────────────────────────

export const METRIC_DEFINITIONS: MetricDefinition[] = [
  {
    key: "sleepHours",
    label: "Sleep",
    unit: "hours",
    icon: "🛏",
    color: "#6366f1",
    ideal: 8,
    min: 0,
    max: 14,
    step: 0.5,
    category: "sleep",
  },
  {
    key: "sleepQuality",
    label: "Sleep Quality",
    unit: "/10",
    icon: "⭐",
    color: "#818cf8",
    ideal: 8,
    min: 1,
    max: 10,
    step: 1,
    category: "sleep",
  },
  {
    key: "waterLiters",
    label: "Water Intake",
    unit: "liters",
    icon: "💧",
    color: "#22d3ee",
    ideal: 2.5,
    min: 0,
    max: 6,
    step: 0.25,
    category: "health",
  },
  {
    key: "studyHours",
    label: "Study / Work",
    unit: "hours",
    icon: "📚",
    color: "#a78bfa",
    ideal: 6,
    min: 0,
    max: 16,
    step: 0.5,
    category: "focus",
  },
  {
    key: "exerciseMinutes",
    label: "Exercise",
    unit: "minutes",
    icon: "🏋",
    color: "#10b981",
    ideal: 45,
    min: 0,
    max: 180,
    step: 5,
    category: "fitness",
  },
  {
    key: "mood",
    label: "Mood",
    unit: "/10",
    icon: "😊",
    color: "#f59e0b",
    ideal: 8,
    min: 1,
    max: 10,
    step: 1,
    category: "mood",
  },
  {
    key: "energyLevel",
    label: "Energy Level",
    unit: "/10",
    icon: "⚡",
    color: "#fbbf24",
    ideal: 8,
    min: 1,
    max: 10,
    step: 1,
    category: "mood",
  },
  {
    key: "screenTimeHours",
    label: "Screen Time",
    unit: "hours",
    icon: "📱",
    color: "#ef4444",
    ideal: 3,
    min: 0,
    max: 16,
    step: 0.5,
    category: "focus",
    penaltyMetric: true,
  },
  {
    key: "stepsCount",
    label: "Steps",
    unit: "steps",
    icon: "👟",
    color: "#34d399",
    ideal: 10000,
    min: 0,
    max: 30000,
    step: 100,
    category: "fitness",
  },
  {
    key: "caloriesConsumed",
    label: "Calories",
    unit: "kcal",
    icon: "🍎",
    color: "#fb923c",
    ideal: 2000,
    min: 0,
    max: 4000,
    step: 50,
    category: "health",
  },
  {
    key: "meditationMins",
    label: "Meditation",
    unit: "minutes",
    icon: "🧘",
    color: "#c084fc",
    ideal: 20,
    min: 0,
    max: 120,
    step: 5,
    category: "mindfulness",
  },
  {
    key: "socialTime",
    label: "Social Time",
    unit: "hours",
    icon: "👥",
    color: "#f472b6",
    ideal: 2,
    min: 0,
    max: 10,
    step: 0.5,
    category: "social",
  },
  {
    key: "journalPages",
    label: "Journaling",
    unit: "pages",
    icon: "📓",
    color: "#a3e635",
    ideal: 2,
    min: 0,
    max: 20,
    step: 1,
    category: "mindfulness",
  },
  {
    key: "gratitudeItems",
    label: "Gratitude",
    unit: "items",
    icon: "🙏",
    color: "#fde68a",
    ideal: 3,
    min: 0,
    max: 10,
    step: 1,
    category: "mindfulness",
  },
];

export const DEFAULT_ENABLED_METRICS = [
  "sleepHours",
  "waterLiters",
  "studyHours",
  "exerciseMinutes",
  "mood",
  "screenTimeHours",
  "stepsCount",
  "meditationMins",
  "socialTime",
];

export function getMetricByKey(key: string): MetricDefinition | undefined {
  return METRIC_DEFINITIONS.find((m) => m.key === key);
}

export const CATEGORY_CONFIG = {
  sleep: { label: "Sleep", icon: "🛏", color: "#6366f1" },
  fitness: { label: "Fitness", icon: "🏋", color: "#10b981" },
  focus: { label: "Focus", icon: "🧠", color: "#a78bfa" },
  health: { label: "Health", icon: "💧", color: "#22d3ee" },
  mood: { label: "Mood", icon: "😊", color: "#f59e0b" },
  mindfulness: { label: "Mindfulness", icon: "🧘", color: "#c084fc" },
  social: { label: "Social", icon: "👥", color: "#f472b6" },
} as const;
